In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
fire_case = pd.read_csv("fire_in_Seoul_2010_2018.csv",
                                thousands=',',
                                encoding='utf-8'
                                ) #thousands는 천단위로 읽었다는 코드

In [6]:
fire_case.head()

,기간,자치구,발생,발생.1,발생.2,발생.3,소실,소실.1,소실.2,피해액,피해액.1,피해액.2,재산피해경감액,인명피해,인명피해.1,인명피해.2,이재민수,구조인원
0,기간,자치구,합계,실화,방화,기타,동수(동),이재가구수(가구),면적(㎡),합계,부동산,동산,재산피해경감액,합계,사망,부상,이재민수,구조인원
1,2010,합계,"5,321","4,395",524,402,"1,563",131,"32,138","14,503,873","5,948,963","8,554,910","1,193,295",230,42,188,277,437
2,2010,종로구,184,159,13,12,45,-,505,"218,556","66,522","152,034","6,983",8,-,8,-,22
3,2010,중구,237,204,9,24,34,4,"1,321","608,296","224,084","384,212","16,451",2,1,1,7,-
4,2010,용산구,160,135,11,14,57,28,"2,728","1,644,922","1,148,703","496,219","6,096",5,1,4,37,9

In [7]:
fire_case

,기간,자치구,발생,발생.1,발생.2,발생.3,소실,소실.1,소실.2,피해액,피해액.1,피해액.2,재산피해경감액,인명피해,인명피해.1,인명피해.2,이재민수,구조인원
0,기간,자치구,합계,실화,방화,기타,동수(동),이재가구수(가구),면적(㎡),합계,부동산,동산,재산피해경감액,합계,사망,부상,이재민수,구조인원
1,2010,합계,"5,321","4,395",524,402,"1,563",131,"32,138","14,503,873","5,948,963","8,554,910","1,193,295",230,42,188,277,437
2,2010,종로구,184,159,13,12,45,-,505,"218,556","66,522","152,034","6,983",8,-,8,-,22
3,2010,중구,237,204,9,24,34,4,"1,321","608,296","224,084","384,212","16,451",2,1,1,7,-
4,2010,용산구,160,135,11,14,57,28,"2,728","1,644,922","1,148,703","496,219","6,096",5,1,4,37,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
230,2018,관악구,337,295,15,27,109,11,"1,772","816,562","395,475","421,087","9,952,527",21,1,20,21,53
231,2018,서초구,242,210,6,26,48,3,"2,223","848,067","201,149","646,918","18,257,199",15,-,15,3,63
232,2018,강남구,436,399,7,30,134,1,"1,631","1,624,983","670,429","954,554","87,651,462",23,-,23,1,36
233,2018,송파구,340,301,7,32,84,16,"2,717","970,251","390,994","579,257","16,546,317",28,-,28,42,99
234,2018,강동구,324,297,14,13,59,8,"3,358","540,625","236,181","304,444","7,235,347",19,4,15,19,26

In [8]:
#주제 : 
#1. 구별 화재 발생 건수 비교
#2. 구별 소방서 개수

In [ ]:
#