In [1]:




import pandas as pd

In [2]:
import numpy as np

In [4]:
crime_anal_police = pd.read_csv("02. crime_in_Seoul.csv",
                                thousands=',',
                                encoding='euc-kr'
                                ) #thousands는 천단위로 읽었다는 코드

In [5]:
crime_anal_police.head()

    관서명  살인 발생  살인 검거  강도 발생  강도 검거  강간 발생  강간 검거  절도 발생  절도 검거  폭력 발생  폭력 검거
0   중부서      2      2      3      2    105     65   1395    477   1355   1170
1   종로서      3      3      6      5    115     98   1070    413   1278   1070
2  남대문서      1      0      6      4     65     46   1153    382    869    794
3  서대문서      2      2      5      4    154    124   1812    738   2056   1711
4   혜화서      3      2      5      4     96     63   1114    424   1015    861

In [6]:
#API 읽기 위해선 Pip install -> 
!pip install googlemaps

Collecting googlemaps
  Downloading https://files.pythonhosted.org/packages/cb/87/5cbe65cd19defe67472db7afd84963a77fbbbe4a764320a67d4a64282b61/googlemaps-4.4.1.tar.gz
Requirement already satisfied: requests<3.0,>=2.20.0 in c:\programdata\anaconda3\lib\site-packages (from googlemaps) (2.22.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (2019.9.11)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (1.24.2)
Requirement already satisfied: idna<2.9,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests<3.0,>=2.20.0->googlemaps) (3.0.4)
Building wheels for collected packages: googlemaps
  Building wheel for googlemaps (setup.py): started
  Building wheel for googlemaps (setup.py): finished with status 'done'
  Created wheel for googlemaps: filename=googlemaps-4.4.1-cp37-none-any.whl size=37825 sha256=ec32262d0bf4d1944b11c081debd4cfb4b3c2cdc7ef650999ad2667de8d4e95a
  Stored in directory: C:\Users\Administrator\AppData\Local\pip\Cache\wheels\5c\ec\b9\9d0c26b80d7dcf16496c82e8108c93186c6d4df097a41bba4f
Successfully built googlemaps
Installing collected packages: googlemaps
Successfully installed googlemaps-4.4.1

In [7]:
import googlemaps

In [9]:
gmaps_key = 'AIzaSyCxF9p0e18rdjf1MXyTVK3evaKUeRXmFG0' #키 값 넣기
gmaps = googlemaps.Client(key=gmaps_key)

In [21]:
#객체 안에 담겨옴
gmaps.geocode('신촌역',language='ko')

[{'address_components': [{'long_name': '신촌',
    'short_name': '신촌',
    'types': ['establishment',
     'point_of_interest',
     'subway_station',
     'transit_station']},
   {'long_name': '신촌동',
    'short_name': '신촌동',
    'types': ['political', 'sublocality', 'sublocality_level_2']},
   {'long_name': '서울특별시',
    'short_name': '서울특별시',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '120-140',
    'short_name': '120-140',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 서울특별시 신촌동 신촌',
  'geometry': {'location': {'lat': 37.559778, 'lng': 126.942325},
   'location_type': 'GEOMETRIC_CENTER',
   'viewport': {'northeast': {'lat': 37.5611269802915,
     'lng': 126.9436739802915},
    'southwest': {'lat': 37.55842901970851, 'lng': 126.9409760197085}}},
  'place_id': 'ChIJ0RGmEpCYfDURAziCwM4_WcU',
  'plus_code': {'compound_code': 'HW5R+WW 대한민국 서울특별시',
   'global_code': '8Q98HW5R+WW'},
  'types': ['establishment',
   'point_of_interest',
   'subway_station',
   'transit_station']},
 {'address_components': [{'long_name': '신촌역2호선',
    'short_name': '신촌역2호선',
    'types': ['establishment', 'point_of_interest', 'transit_station']},
   {'long_name': '신촌동',
    'short_name': '신촌동',
    'types': ['political', 'sublocality', 'sublocality_level_2']},
   {'long_name': '서울특별시',
    'short_name': '서울특별시',
    'types': ['administrative_area_level_1', 'political']},
   {'long_name': '대한민국',
    'short_name': 'KR',
    'types': ['country', 'political']},
   {'long_name': '120-180',
    'short_name': '120-180',
    'types': ['postal_code']}],
  'formatted_address': '대한민국 서울특별시 신촌동 신촌역2호선',
  'geometry': {'location': {'lat': 37.5562944, 'lng': 126.9399855},
   'location_type': 'GEOMETRIC_CENTER',
   'viewport': {'northeast': {'lat': 37.55764338029149,
     'lng': 126.9413344802915},
    'southwest': {'lat': 37.5549454197085, 'lng': 126.9386365197085}}},
  'place_id': 'ChIJ8SSo3JaYfDURkfjQoKuHBmE',
  'plus_code': {'compound_code': 'HW4Q+GX 대한민국 서울특별시',
   'global_code': '8Q98HW4Q+GX'},
  'types': ['establishment', 'point_of_interest', 'transit_station']}]

In [22]:
#문자 인덱스 -1 로 뒷자리 '서' -> 경찰서로 바꾸자
station_name = []
#name[:-1] 은 맨앞부터 -> 뒷자리 하나 빼고까지
for name in crime_anal_police['관서명'] :
    station_name.append('서울' + name[:-1] + '경찰서')

station_name

['서울중부경찰서',
 '서울종로경찰서',
 '서울남대문경찰서',
 '서울서대문경찰서',
 '서울혜화경찰서',
 '서울용산경찰서',
 '서울성북경찰서',
 '서울동대문경찰서',
 '서울마포경찰서',
 '서울영등포경찰서',
 '서울성동경찰서',
 '서울동작경찰서',
 '서울광진경찰서',
 '서울서부경찰서',
 '서울강북경찰서',
 '서울금천경찰서',
 '서울중랑경찰서',
 '서울강남경찰서',
 '서울관악경찰서',
 '서울강서경찰서',
 '서울강동경찰서',
 '서울종암경찰서',
 '서울구로경찰서',
 '서울서초경찰서',
 '서울양천경찰서',
 '서울송파경찰서',
 '서울노원경찰서',
 '서울방배경찰서',
 '서울은평경찰서',
 '서울도봉경찰서',
 '서울수서경찰서']

In [23]:
#각 경찰서 별 전체 주소 리스트
#각 경찰서 별 위도 리스트 
#각 경찰서 별 경도 리스트
station_address = []
station_lat = []
station_lng = []

#딕셔너리 리스트에서 끄내주자
#get 메소드는 '키' 에서 끄냅니다.
for name in station_name:
    tmp = gmaps.geocode(name, language='ko')
    station_address.append(tmp[0].get('formatted_address'))
    tmp_loc = tmp[0].get('geometry')
    station_lat.append(tmp_loc['location']['lat'])
    station_lng.append(tmp_loc['location']['lng'])
    
    print(name + '-->' + tmp[0].get('formatted_address'))

서울중부경찰서-->대한민국 서울특별시 중구 을지로동 수표로 27
서울종로경찰서-->대한민국 서울특별시 종로구 종로1.2.3.4가동 율곡로 46
서울남대문경찰서-->대한민국 서울특별시 중구 회현동 한강대로 410
서울서대문경찰서-->대한민국 서울특별시 서대문구 충현동 통일로 113
서울혜화경찰서-->대한민국 서울특별시 종로구 인의동 창경궁로 112-16
서울용산경찰서-->대한민국 서울특별시 용산구 원효로1가 백범로 329
서울성북경찰서-->대한민국 서울특별시 성북구 삼선동5가 301
서울동대문경찰서-->대한민국 서울특별시 동대문구 청량리동 약령시로21길 29
서울마포경찰서-->대한민국 서울특별시 마포구 아현동 마포대로 183
서울영등포경찰서-->대한민국 서울특별시 영등포구 영등포동1가 618-7
서울성동경찰서-->대한민국 서울특별시 성동구 행당동 왕십리광장로 9
서울동작경찰서-->대한민국 서울특별시 동작구 노량진1동 노량진로 148
서울광진경찰서-->대한민국 서울특별시 광진구 구의동 자양로 167
서울서부경찰서-->대한민국 서울특별시 은평구 신사2동 184-56
서울강북경찰서-->대한민국 서울특별시 강북구 번1동 오패산로 406
서울금천경찰서-->대한민국 서울특별시 금천구 시흥동 190
서울중랑경찰서-->대한민국 서울특별시 중랑구 망우동 489-7
서울강남경찰서-->대한민국 서울특별시 강남구 대치동 998
서울관악경찰서-->대한민국 서울특별시 관악구 봉천동
서울강서경찰서-->대한민국 서울특별시 강서구 화곡6동 980-15
서울강동경찰서-->대한민국 서울특별시 강동구 성내1동 성내로 57
서울종암경찰서-->대한민국 서울특별시 성북구 종암동 종암로 135
서울구로경찰서-->대한민국 서울특별시 구로구 구로동 가마산로 235
서울서초경찰서-->대한민국 서울특별시 서초구 서초3동 반포대로 179
서울양천경찰서-->대한민국 서울특별시 양천구 신정6동 목동동로 99
서울송파경찰서-->대한민국 서울특별시 송파구 가락본동 9
서울노원경찰서-->대한민국 서울특별시 노원구 하계동 노원로 283
서울방배경찰서-->대한민국 서울특별시 서초구 방배본동 동작대로 204
서울은평경찰서-->대한민국 서울특별시 은평구 불광동 연서로 365
서울도봉경찰서-->대한민국 서울특별시 도봉구 창4동 노해로 403
서울수서경찰서-->대한민국 서울특별시 강남구 개포동 개포로 617

In [25]:
#경찰서 주소
station_address

['대한민국 서울특별시 중구 을지로동 수표로 27',
 '대한민국 서울특별시 종로구 종로1.2.3.4가동 율곡로 46',
 '대한민국 서울특별시 중구 회현동 한강대로 410',
 '대한민국 서울특별시 서대문구 충현동 통일로 113',
 '대한민국 서울특별시 종로구 인의동 창경궁로 112-16',
 '대한민국 서울특별시 용산구 원효로1가 백범로 329',
 '대한민국 서울특별시 성북구 삼선동5가 301',
 '대한민국 서울특별시 동대문구 청량리동 약령시로21길 29',
 '대한민국 서울특별시 마포구 아현동 마포대로 183',
 '대한민국 서울특별시 영등포구 영등포동1가 618-7',
 '대한민국 서울특별시 성동구 행당동 왕십리광장로 9',
 '대한민국 서울특별시 동작구 노량진1동 노량진로 148',
 '대한민국 서울특별시 광진구 구의동 자양로 167',
 '대한민국 서울특별시 은평구 신사2동 184-56',
 '대한민국 서울특별시 강북구 번1동 오패산로 406',
 '대한민국 서울특별시 금천구 시흥동 190',
 '대한민국 서울특별시 중랑구 망우동 489-7',
 '대한민국 서울특별시 강남구 대치동 998',
 '대한민국 서울특별시 관악구 봉천동',
 '대한민국 서울특별시 강서구 화곡6동 980-15',
 '대한민국 서울특별시 강동구 성내1동 성내로 57',
 '대한민국 서울특별시 성북구 종암동 종암로 135',
 '대한민국 서울특별시 구로구 구로동 가마산로 235',
 '대한민국 서울특별시 서초구 서초3동 반포대로 179',
 '대한민국 서울특별시 양천구 신정6동 목동동로 99',
 '대한민국 서울특별시 송파구 가락본동 9',
 '대한민국 서울특별시 노원구 하계동 노원로 283',
 '대한민국 서울특별시 서초구 방배본동 동작대로 204',
 '대한민국 서울특별시 은평구 불광동 연서로 365',
 '대한민국 서울특별시 도봉구 창4동 노해로 403',
 '대한민국 서울특별시 강남구 개포동 개포로 617']

In [26]:
#station_lng
station_lng

[126.9895796,
 126.9848674,
 126.9734981,
 126.9667762,
 126.9989143,
 126.9659183,
 127.0161353,
 127.0457679,
 126.954028,
 126.905728,
 127.0363806,
 126.9428498,
 127.083821,
 126.9053648,
 127.0273399,
 126.8970429,
 127.0956516,
 127.0669578,
 126.9509748,
 126.8499269,
 127.1268224,
 127.0321577,
 126.886731,
 127.0052504,
 126.8656763,
 127.1271513,
 127.0717076,
 126.9831279,
 126.9287226,
 127.052682,
 127.0772119]

In [27]:
#station_lat
station_lat

[37.5636465,
 37.5755578,
 37.5547584,
 37.5647848,
 37.5718529,
 37.5387099,
 37.5897482,
 37.58506149999999,
 37.550814,
 37.5153176,
 37.5617309,
 37.5130866,
 37.542873,
 37.591836,
 37.63730390000001,
 37.4568722,
 37.5990885,
 37.5094352,
 37.4743789,
 37.5516732,
 37.528511,
 37.6020592,
 37.494931,
 37.4956054,
 37.5165667,
 37.5019065,
 37.6425238,
 37.4945959,
 37.6283597,
 37.6533589,
 37.49349]

In [59]:
#full string -> 반복문 -> equals -> 단어 추출 -> '구' 만 뽑자

for name in station_address :
        tmp = name.split()
        for x in tmp : 

#     for y in tmp :
#         print(y)
#lamda 를 쓰면 간단하게 해당 내용을 뽑아냄
# gu_name = []
# for name in station_address:
#     tmp = name.split() #split 공백은 ' ' 그냥 넣어두됨
#     for x in tmp: #tmp 는 공백으로 나눠진 단어들 리스트 
#         print(x[0])

['대한민국', '서울특별시', '중구', '을지로동', '수표로', '27']
['대한민국', '서울특별시', '종로구', '종로1.2.3.4가동', '율곡로', '46']
['대한민국', '서울특별시', '중구', '회현동', '한강대로', '410']
['대한민국', '서울특별시', '서대문구', '충현동', '통일로', '113']
['대한민국', '서울특별시', '종로구', '인의동', '창경궁로', '112-16']
['대한민국', '서울특별시', '용산구', '원효로1가', '백범로', '329']
['대한민국', '서울특별시', '성북구', '삼선동5가', '301']
['대한민국', '서울특별시', '동대문구', '청량리동', '약령시로21길', '29']
['대한민국', '서울특별시', '마포구', '아현동', '마포대로', '183']
['대한민국', '서울특별시', '영등포구', '영등포동1가', '618-7']
['대한민국', '서울특별시', '성동구', '행당동', '왕십리광장로', '9']
['대한민국', '서울특별시', '동작구', '노량진1동', '노량진로', '148']
['대한민국', '서울특별시', '광진구', '구의동', '자양로', '167']
['대한민국', '서울특별시', '은평구', '신사2동', '184-56']
['대한민국', '서울특별시', '강북구', '번1동', '오패산로', '406']
['대한민국', '서울특별시', '금천구', '시흥동', '190']
['대한민국', '서울특별시', '중랑구', '망우동', '489-7']
['대한민국', '서울특별시', '강남구', '대치동', '998']
['대한민국', '서울특별시', '관악구', '봉천동']
['대한민국', '서울특별시', '강서구', '화곡6동', '980-15']
['대한민국', '서울특별시', '강동구', '성내1동', '성내로', '57']
['대한민국', '서울특별시', '성북구', '종암동', '종암로', '135']
['대한민국', '서울특별시', '구로구', '구로동', '가마산로', '235']
['대한민국', '서울특별시', '서초구', '서초3동', '반포대로', '179']
['대한민국', '서울특별시', '양천구', '신정6동', '목동동로', '99']
['대한민국', '서울특별시', '송파구', '가락본동', '9']
['대한민국', '서울특별시', '노원구', '하계동', '노원로', '283']
['대한민국', '서울특별시', '서초구', '방배본동', '동작대로', '204']
['대한민국', '서울특별시', '은평구', '불광동', '연서로', '365']
['대한민국', '서울특별시', '도봉구', '창4동', '노해로', '403']
['대한민국', '서울특별시', '강남구', '개포동', '개포로', '617']

['대한민국', '서울특별시', '강남구', '개포동', '개포로', '617']

In [41]:
gu_name = []
#이중 for문으로 [ [], [], []  ] 끄냄
for name in station_address:
        tmp = name.split()
        for x in tmp:
            #print(x)
            if(x[-1] == '구'):
                gu_name.append([x]) 
        print('-------------')
print(gu_name)

-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
-------------
[['중구'], ['종로구'], ['중구'], ['서대문구'], ['종로구'], ['용산구'], ['성북구'], ['동대문구'], ['마포구'], ['영등포구'], ['성동구'], ['동작구'], ['광진구'], ['은평구'], ['강북구'], ['금천구'], ['중랑구'], ['강남구'], ['관악구'], ['강서구'], ['강동구'], ['성북구'], ['구로구'], ['서초구'], ['양천구'], ['송파구'], ['노원구'], ['서초구'], ['은평구'], ['도봉구'], ['강남구']]

In [60]:
#lamda 갓을 쓰면 요런 이중 for문을 쉽게 해결함

gu_name = []
for name in station_address:
    tmp=name.split()
    tmp_gu = [x for x in tmp if x[-1] == '구'][0]
    #select x,  for x in tmp, if [x-1], return -> [0] 일케 써야 하나의 리스트를 뽑는게 아니라, 리스트 index 0번으로 뽑음
    #차이는 리스트를 뽑느냐, 리스트의 [0] 를 뽑느냐 -> 스트링이겠죠
    #x에다가 + "역" 붙이면 ex)종로구역 같이 뽑을 수 있음
    gu_name.append(tmp_gu)
    print(tmp_gu)

중구
종로구
중구
서대문구
종로구
용산구
성북구
동대문구
마포구
영등포구
성동구
동작구
광진구
은평구
강북구
금천구
중랑구
강남구
관악구
강서구
강동구
성북구
구로구
서초구
양천구
송파구
노원구
서초구
은평구
도봉구
강남구

In [62]:
crime_anal_police['구별'] = gu_name

In [63]:
crime_anal_police.head()

,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [64]:
crime_anal_police.to_csv('../crime_in_Seoul_include_gu_name.csv', sep=',', encoding = 'utf-8') # CSV 파일로 저장

In [65]:
crime_anal_raw = pd.read_csv('../crime_in_Seoul_include_gu_name.csv', sep=',', encoding='utf-8')

In [73]:
crime_anal_raw.head()

,Unnamed: 0,관서명,살인 발생,살인 검거,강도 발생,강도 검거,강간 발생,강간 검거,절도 발생,절도 검거,폭력 발생,폭력 검거,구별
0,0,중부서,2,2,3,2,105,65,1395,477,1355,1170,중구
1,1,종로서,3,3,6,5,115,98,1070,413,1278,1070,종로구
2,2,남대문서,1,0,6,4,65,46,1153,382,869,794,중구
3,3,서대문서,2,2,5,4,154,124,1812,738,2056,1711,서대문구
4,4,혜화서,3,2,5,4,96,63,1114,424,1015,861,종로구

In [74]:
#pivot(피봇) : 요약 ->  group by 비슷한 개념인듯
crime_anal = pd.pivot_table(crime_anal_raw, index='구별', aggfunc=np.sum) #'구별' 로 요약을 묶어서 np.sum 해줘 (mean도 있고 다른것도 있는듯)
crime_anal.head()

,Unnamed: 0,강간 검거,강간 발생,강도 검거,강도 발생,살인 검거,살인 발생,절도 검거,절도 발생,폭력 검거,폭력 발생
구별,,,,,,,,,,,
강남구,47,349,449,18,21,10,13,1650,3850,3705,4284
강동구,20,123,156,8,6,3,4,789,2366,2248,2712
강북구,14,126,153,13,14,8,7,618,1434,2348,2649
강서구,19,191,262,13,13,8,7,1260,2096,2718,3207
관악구,18,221,320,14,12,8,9,827,2706,2642,3298

In [76]:
crime_anal['강간검거율'] = crime_anal['강간 검거'] / crime_anal['강간 발생'] * 100 
crime_anal['강도검거율'] = crime_anal['강도 검거'] / crime_anal['강도 발생'] * 100 
crime_anal['살인검거율'] = crime_anal['살인 검거'] / crime_anal['살인 발생'] * 100 
crime_anal['절도검거율'] = crime_anal['절도 검거'] / crime_anal['절도 발생'] * 100 
crime_anal['폭력검거율'] = crime_anal['폭력 검거'] / crime_anal['폭력 발생'] * 100

In [77]:
crime_anal

,Unnamed: 0,강간 검거,강간 발생,강도 검거,강도 발생,살인 검거,살인 발생,절도 검거,절도 발생,폭력 검거,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,,,,,,
강남구,47,349,449,18,21,10,13,1650,3850,3705,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,20,123,156,8,6,3,4,789,2366,2248,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,14,126,153,13,14,8,7,618,1434,2348,2649,82.352941,92.857143,114.285714,43.096234,88.637222
강서구,19,191,262,13,13,8,7,1260,2096,2718,3207,72.900763,100.000000,114.285714,60.114504,84.752105
관악구,18,221,320,14,12,8,9,827,2706,2642,3298,69.062500,116.666667,88.888889,30.561715,80.109157
광진구,12,220,240,26,14,4,4,1277,3026,2180,2625,91.666667,185.714286,100.000000,42.200925,83.047619
구로구,22,164,281,11,15,6,8,889,2335,2432,3007,58.362989,73.333333,75.000000,38.072805,80.877951
금천구,15,122,151,6,6,4,3,888,1567,1776,2054,80.794702,100.000000,133.333333,56.668794,86.465433
노원구,26,121,197,7,7,10,10,801,2193,2329,2723,61.421320,100.000000,100.000000,36.525308,85.530665
도봉구,29,106,102,10,9,3,3,478,1063,1303,1487,103.921569,111.111111,100.000000,44.967074,87.626093
동대문구,7,146,173,13,13,5,5,814,1981,2227,2548,84.393064,100.000000,100.000000,41.090358,87.401884
동작구,11,139,285,5,9,5,5,661,1865,1587,1910,48.771930,55.555556,100.000000,35.442359,83.089005
마포구,8,247,294,10,14,8,8,813,2555,2519,2983,84.013605,71.428571,100.000000,31.819961,84.445189
서대문구,3,124,154,4,5,2,2,738,1812,1711,2056,80.519481,80.000000,100.000000,40.728477,83.219844
서초구,50,249,393,6,9,6,8,1091,2635,2098,2399,63.358779,66.666667,75.000000,41.404175,87.453105
성동구,10,119,126,8,9,4,4,597,1607,1395,1612,94.444444,88.888889,100.000000,37.149969,86.538462
성북구,27,124,150,4,5,5,5,741,1785,1855,2209,82.666667,80.000000,100.000000,41.512605,83.974649
송파구,25,178,220,10,13,10,11,1129,3239,2786,3295,80.909091,76.923077,90.909091,34.856437,84.552352
양천구,24,105,120,3,6,5,3,672,1890,2030,2509,87.500000,50.000000,166.666667,35.555556,80.908729
영등포구,9,183,295,20,22,12,14,978,2964,2961,3572,62.033898,90.909091,85.714286,32.995951,82.894737
용산구,5,173,194,14,14,5,5,587,1557,1704,2050,89.175258,100.000000,100.000000,37.700706,83.121951
은평구,41,141,166,6,9,3,3,711,1914,2306,2653,84.939759,66.666667,100.000000,37.147335,86.920467
종로구,5,161,211,9,11,5,6,837,2184,1931,2293,76.303318,81.818182,83.333333,38.324176,84.212822
중구,2,111,170,6,9,2,3,859,2548,1964,2224,65.294118,66.666667,66.666667,33.712716,88.309353
중랑구,16,148,187,9,11,12,13,829,2135,2407,2847,79.144385,81.818182,92.307692,38.829040,84.545135

In [78]:
del crime_anal['강간 검거']
del crime_anal['강도 검거']
del crime_anal['절도 검거']
del crime_anal['살인 검거']
del crime_anal['폭력 검거']

In [79]:
crime_anal.head()

,Unnamed: 0,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,
강남구,47,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,20,156,6,4,2366,2712,78.846154,133.333333,75.000000,33.347422,82.890855
강북구,14,153,14,7,1434,2649,82.352941,92.857143,114.285714,43.096234,88.637222
강서구,19,262,13,7,2096,3207,72.900763,100.000000,114.285714,60.114504,84.752105
관악구,18,320,12,9,2706,3298,69.062500,116.666667,88.888889,30.561715,80.109157

In [81]:
#이상값 처리를 위한 for문 
con_list = ['강간검거율', '살인검거율', '절도검거율', '폭력검거율', '강도검거율']
for column in con_list :
    crime_anal.loc[crime_anal[column] > 100, column] = 100
#항목명을 알때는 loc 함수를 이용해준다.

In [82]:
crime_anal.head()

,Unnamed: 0,강간 발생,강도 발생,살인 발생,절도 발생,폭력 발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,
강남구,47,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,20,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,14,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
강서구,19,262,13,7,2096,3207,72.900763,100.000000,100.000000,60.114504,84.752105
관악구,18,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157

In [84]:
crime_anal.rename(columns= {
    '강간 발생' : '강간',
    '강도 발생' : '강도',
    '살인 발생' : '살인',
    '절도 발생' : '절도',
    '폭력 발생' : '폭력'},
    inplace=True
)

In [85]:
crime_anal.head()

,Unnamed: 0,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,
강남구,47,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,20,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,14,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
강서구,19,262,13,7,2096,3207,72.900763,100.000000,100.000000,60.114504,84.752105
관악구,18,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157

In [89]:
del crime_anal['Unnamed: 0']
crime_anal.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
강서구,262,13,7,2096,3207,72.900763,100.000000,100.000000,60.114504,84.752105
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157

In [90]:
crime_anal

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,449,21,13,3850,4284,77.728285,85.714286,76.923077,42.857143,86.484594
강동구,156,6,4,2366,2712,78.846154,100.000000,75.000000,33.347422,82.890855
강북구,153,14,7,1434,2649,82.352941,92.857143,100.000000,43.096234,88.637222
강서구,262,13,7,2096,3207,72.900763,100.000000,100.000000,60.114504,84.752105
관악구,320,12,9,2706,3298,69.062500,100.000000,88.888889,30.561715,80.109157
광진구,240,14,4,3026,2625,91.666667,100.000000,100.000000,42.200925,83.047619
구로구,281,15,8,2335,3007,58.362989,73.333333,75.000000,38.072805,80.877951
금천구,151,6,3,1567,2054,80.794702,100.000000,100.000000,56.668794,86.465433
노원구,197,7,10,2193,2723,61.421320,100.000000,100.000000,36.525308,85.530665
도봉구,102,9,3,1063,1487,100.000000,100.000000,100.000000,44.967074,87.626093
동대문구,173,13,5,1981,2548,84.393064,100.000000,100.000000,41.090358,87.401884
동작구,285,9,5,1865,1910,48.771930,55.555556,100.000000,35.442359,83.089005
마포구,294,14,8,2555,2983,84.013605,71.428571,100.000000,31.819961,84.445189
서대문구,154,5,2,1812,2056,80.519481,80.000000,100.000000,40.728477,83.219844
서초구,393,9,8,2635,2399,63.358779,66.666667,75.000000,41.404175,87.453105
성동구,126,9,4,1607,1612,94.444444,88.888889,100.000000,37.149969,86.538462
성북구,150,5,5,1785,2209,82.666667,80.000000,100.000000,41.512605,83.974649
송파구,220,13,11,3239,3295,80.909091,76.923077,90.909091,34.856437,84.552352
양천구,120,6,3,1890,2509,87.500000,50.000000,100.000000,35.555556,80.908729
영등포구,295,22,14,2964,3572,62.033898,90.909091,85.714286,32.995951,82.894737
용산구,194,14,5,1557,2050,89.175258,100.000000,100.000000,37.700706,83.121951
은평구,166,9,3,1914,2653,84.939759,66.666667,100.000000,37.147335,86.920467
종로구,211,11,6,2184,2293,76.303318,81.818182,83.333333,38.324176,84.212822
중구,170,9,3,2548,2224,65.294118,66.666667,66.666667,33.712716,88.309353
중랑구,187,11,13,2135,2847,79.144385,81.818182,92.307692,38.829040,84.545135

In [91]:
#1. 살인/전체인구 -> 살인율..
#2. 살인 / (살인+폭력) = 상해 * 100 -> 전체 상해 발새 대비 살인발생
#3. 경찰 성과 지표 : 전체 검거율/5 -> 동작구가 제일 심해보임..(경찰청에 전화하자)